---
title: '*cool project name here*'
output:
  html_document:
    df_print: paged
authors: todos
---

----
libraries here 
```{r}
library(readxl)
library(classdata)
library(tidyverse)
library(stringr)
library(ggplot2)
library(plotly)
```

----
import data here
```{r}
fight_songs = read.csv('fight-songs.csv')
ipeds <- read_excel('IPEDS_data.xlsx', sheet='Data')
lookup_table = read.csv('lookup_table.csv')
```
----
cleaning data (VERSION 1)

1) loop through all values ipeds and fight_songs

2) add if similar name, otherwise print which names did not work
```{r}
cleaned_ipeds <- data.frame()
i <- 1
for (name in fight_songs$school){
  if (!is.na(pmatch(name, ipeds$Name, duplicates.ok = FALSE))){
    picked_row <- (pmatch(name, ipeds$Name))
    foo <- paste("works: ", name)
    foo <- paste(foo, ipeds$Name[picked_row])
    print(foo)
   
    cleaned_ipeds <- rbind(cleaned_ipeds, ipeds[picked_row,] )
  }
  else{
    foo <- paste("doesn't work: ", name)
    # print(foo)
  }
}

for(row in 1:nrow(lookup_table)){
  location <- lookup_table$Column[row]
  i <- i + 1
  cleaned_ipeds <- rbind(cleaned_ipeds, ipeds[location,] )
}

```
----
cleaning the data (VERSION 2!)
added a new column for the IDs in ipeds. allows for better, through cleaning. Some words weren't used correctly in pmatch.
```{r}

for (id in fight_songs$"ID Number"){
  if (!is.na(match(name, ipeds$"ID Number"))){
    picked_row <- (match(name, ipeds$"ID Number"))
    foo <- paste("works: ", name)
    cleaned_ipeds <- rbind(cleaned_ipeds, ipeds[picked_row,] )
  }
  else{
    print("ERROR")
  }
}
cleaned_ipeds
fight_songs$ID.number <- as.double(fight_songs$ID.number)

names(fight_songs)[28] <- "ID number"

fight_songs

```

----
joining the data
```{r}
cleaned_ipeds$year <- NULL

join_data <- left_join(cleaned_ipeds, fight_songs)
```

----
jessies part
```{r}
join_data2 <- left_join(fight_songs, cleaned_ipeds)

colnames(join_data2)

speed_plot <- join_data2 %>%
  mutate('conference' = as.factor(join_data2$conference)) %>%
  ggplot(aes(x = sec_duration, y = bpm, color = join_data2$conference, text = paste0("<b>Song Name: </b>", join_data2$song_name, "<br>", "<b>School: <b>", join_data2$school))) +
  geom_point() +
  geom_hline(yintercept = median(join_data2$bpm)) +
  geom_vline(xintercept = median(join_data2$sec_duration)) +
  xlab("Song Length (Seconds)") +
  ylab("Song Speed (bpm)") +
  scale_colour_brewer(palette = "Set1") +
  theme(panel.grid = element_blank())

speed_plotly <- ggplotly(speed_plot, tooltip = "text") %>%
  hide_legend()

speed_plotly

join_data2 <- join_data2 %>%
  mutate(speed_cat = if_else(join_data2$bpm < 140 && join_data2$sec_duration < 67, 'Short & Slow', 'Long & Fast')) %>%
  mutate(speed_cat = if_else(join_data2$bpm < 140 && join_data2$sec_duration > 67, 'Long & Slow', 'Long & Fast')) %>%
  mutate(speed_catt = if_else(join_data2$bpm > 140 && join_data2$sec_duration < 67, 'Short & Fast', 'Long & Fast'))

map <- map_data('state')

map %>%
  ggplot(aes(x=long, y=lat)) + 
  geom_path(aes(group=group)) + 
   geom_point(data = join_data2, 
             aes(x = join_data2$'Longitude location of institution', y = join_data2$'Latitude location of institution')) +
  coord_map()
```

----
henrys part
```{r}

```

----
matthews part
```{r}

```

----
anns part (if doing more than cleaning)
```{r}

```



